export const Currencies = [
  { value: "USD", label: "$ Dollar", locale: "en-US" },
  { value: "EUR", label: "€ Euro", locale: "de-DE" },
  { value: "GBP", label: "£ Pound", locale: "en-GB" },
  { value: "JPY", label: "¥ Yen", locale: "ja-JP" },
  { value: "RUB", label: "₽ Ruble", locale: "ru-RU" },
  { value: "BRL", label: "R$ Real", locale: "pt-BR" },
  { value: "CNY", label: "¥ Yuan", locale: "zh-CN" },
  { value: "BDT", label: "৳ Taka", locale: "bn-BD" },
  { value: "INR", label: "₹ Rupee", locale: "hi-IN" },
  { value: "IDR", label: "Rp Rupiah", locale: "id-ID" },
  { value: "KRW", label: "₩ Won", locale: "ko-KR" },
  { value: "MXN", label: "$ Peso", locale: "es-MX" },
  { value: "NZD", label: "$ Dollar", locale: "en-NZ" },
  { value: "TRY", label: "₺ Lira", locale: "tr-TR" },
  { value: "ZAR", label: "R Rand", locale: "af-ZA" },
  { value: "ILS", label: "₪ Shekel", locale: "he-IL" },
  { value: "THB", label: "฿ Baht", locale: "th-TH" },
  { value: "VND", label: "₫ Dong", locale: "vi-VN" },
  { value: "MYR", label: "RM Ringgit", locale: "ms-MY" },
  { value: "CZK", label: "Kč Koruna", locale: "cs-CZ" },
  { value: "DKK", label: "kr Krone", locale: "da-DK" },
  { value: "HUF", label: "Ft Forint", locale: "hu-HU" },
  { value: "PLN", label: "zł Zloty", locale: "pl-PL" },
  { value: "SGD", label: "$ Singapore Dollar", locale: "en-SG" },
  { value: "AUD", label: "$ Australian Dollar", locale: "en-AU" },
  { value: "CAD", label: "$ Canadian Dollar", locale: "en-CA" },
  { value: "CHF", label: "CHF Franc", locale: "de-CH" },
  { value: "SEK", label: "kr Krona", locale: "sv-SE" },
  { value: "NOK", label: "kr Krone", locale: "nb-NO" },
  { value: "AED", label: "د.إ Dirham", locale: "ar-AE" },
  { value: "SAR", label: "﷼ Riyal", locale: "ar-SA" },
  { value: "HKD", label: "$ Hong Kong Dollar", locale: "en-HK" },
  { value: "PKR", label: "₨ Rupee", locale: "ur-PK" },
  { value: "EGP", label: "£ Pound", locale: "ar-EG" },
  { value: "NGN", label: "₦ Naira", locale: "en-NG" },
  { value: "KES", label: "KSh Shilling", locale: "en-KE" },
  { value: "TZS", label: "TSh Shilling", locale: "sw-TZ" },
  { value: "UGX", label: "USh Shilling", locale: "sw-UG" },
  { value: "GHS", label: "₵ Cedi", locale: "en-GH" },
  { value: "XAF", label: "FCFA Franc", locale: "fr-CM" },
  { value: "XOF", label: "CFA Franc", locale: "fr-SN" },
  { value: "LKR", label: "₨ Rupee", locale: "si-LK" },
  { value: "PHP", label: "₱ Peso", locale: "en-PH" },
  { value: "COP", label: "$ Peso", locale: "es-CO" },
  { value: "ARS", label: "$ Peso", locale: "es-AR" },
  { value: "CLP", label: "$ Peso", locale: "es-CL" },
];

export type Currency = (typeof Currencies)[0];
